name: Python Script Execution

on:
  pull_request:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    # Check out repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python 3.10
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    # Display Python version for verification
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
      
    # Install dependencies from requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    # Run your Python script
    - name: Run script
      run: python src/1_get_data_previous_game_day.py
