name: 🏀Run Script 3 - LightGBM prediction script

# Run on every push to main, and also every day at 08:00 UTC
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 8 * * *'

jobs:
  predict:
    runs-on: ubuntu-latest
    steps:
      # 1. Pull down your repository
      - uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3. Install dependencies, if you have a requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      # 4. Run your prediction script
      - name: Run LightGBM prediction
        run: |
          python src/3_03052025_lightgbm.py
