name: 🏀 Run Script 3 – LightGBM prediction

on:
 workflow_dispatch:

jobs:
  predict:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

          # now uninstall any leftover wheels and force‐reinstall a matching trio
          pip uninstall -y numpy scikit-learn lightgbm || true
          pip install numpy==1.24.4  \
                      scikit-learn==1.2.2 \
                      lightgbm==3.3.5

      # 4) Run data‐gathering script (must produce Next_Game CSV)
      - name: Run Script 2 – Next Game Data
        run: python src/2_get_data_next_game_day.py

      # 5) Run prediction script (now sees the games_df CSV)
      - name: Run Script 3 – LightGBM prediction
        run: python src/3_lightgbm.py

      # 6) Commit and push BOTH data and predictions
      - name: Commit & push new CSVs
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # add raw next‐game data
          git add output/Gathering_Data/Next_Game/games_df_*.csv || true
          # add your model outputs
          git add output/LightGBM/1_2025_Prediction/nba_games_predict_*.csv || true

          git commit -m "🔄 Update next‐game data & predictions for $(date +'%Y-%m-%d')" \
            || echo "No CSV changes to commit"
          git push origin HEAD:${GITHUB_REF_NAME}
