name: 🏀 Run Script 3 – LightGBM prediction

on:
  push:
    branches:
      - main

jobs:
  predict:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Pin numpy to avoid ABI break
          pip install numpy==1.24.4
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Run LightGBM prediction
        run: python src/3_lightgbm.py

      - name: Commit and push prediction outputs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/LightGBM/1\.\*/nba_games_predict_*.csv
          git commit -m "📈 Add LightGBM predictions for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref_name }}
