name: 🏀 Run Script 4 – Calculate Betting Statistics

on:
  workflow_dispatch:

jobs:
  calc-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          # ensure consistent versions
          pip uninstall -y numpy pandas || true
          pip install numpy==1.24.4 pandas==2.0.3

      - name: Run Script 4 – Calculate Betting Statistics
        run: |
          python calc_betting_stats.py \
            --pred-dir output/LightGBM/1_2025_Prediction \
            --stat-dir output/Gathering_Data/Whole_Statistic

      - name: Commit & push updated stats CSV
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # add the new combined accuracy file(s)
          git add output/LightGBM/1_2025_Prediction/combined_nba_predictions_acc_*.csv || true

          git commit -m "🔄 Update combined betting stats for $(date +'%Y-%m-%d')" \
            || echo "No combined CSV changes to commit"
          git push origin HEAD:${GITHUB_REF_NAME}
