name: Run Script 2 - Next Game Data

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run next game script
      run: python src/2_get_data_next_game_day.py

    - name: Upload result CSV as artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: next-game-csv
        path: output/Gathering_Data/Next_Game/games_df_*.csv

    - name: Commit and push games_df CSV
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add output/Gathering_Data/Next_Game/games_df_*.csv
        git commit -m "Add next game CSV for $(date +'%Y-%m-%d')" || echo "No changes to commit"
        git push
