name: 🏀 Run Script 3 – LightGBM prediction

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  predict:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # pin numpy to a 1.24.x wheel ABI to match sklearn/lightgbm
          pip install numpy==1.24.4
          # install sklearn and lightgbm wheels built against that numpy
          pip install scikit-learn==1.2.2 lightgbm==3.3.5
          # then any other deps you list in requirements.txt
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Run LightGBM prediction
        run: |
          python src/3_lightgbm.py

      - name: Commit and push prediction outputs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/LightGBM/1\.\*/nba_games_predict_*.csv
          git commit -m "📈 Add LightGBM predictions for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref_name }}
