name: 🏀 NBA Data Collection & Prediction Workflow

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write  # Allow bot to push files

jobs:
  nba-data-workflow:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Step 1: Collect Previous Games Data
    - name: Run script 1 - Previous Games Data
      run: python src/1_get_data_previous_game_day.py

    # Step 2: Next Game Data
    - name: Run script 2 - Next Game Data
      run: python src/2_get_data_next_game_day.py

    # Step 3: LightGBM Prediction
    - name: Run Script 3 - LightGBM prediction
      run: python src/3_lightgbm.py

    # Single commit for all changes
    - name: Commit all changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        # Add all generated files
        git add output/Gathering_Data/Whole_Statistic/nba_games_*.csv
        git add output/Gathering_Data/data/2025_standings/*.html
        git add output/Gathering_Data/Next_Game/games_df_*.csv
        git add output/LightGBM/1_2025_Prediction/nba_games_predict_*.csv

        git commit -m "🔄 Update NBA data and predictions for $(date +'%Y-%m-%d')" \
          || echo "No changes to commit"
        git push origin main